In [4]:
import random
random.randint(50,100)

100

In [8]:
import numpy as np
#50學生,5個分數

scores=np.random.randint(50,100,size=(50,5))
scores

array([[78, 82, 93, 94, 73],
       [51, 76, 70, 78, 58],
       [93, 55, 54, 81, 64],
       [54, 52, 88, 51, 65],
       [79, 99, 91, 72, 65],
       [96, 77, 84, 54, 60],
       [70, 67, 54, 94, 72],
       [89, 59, 55, 53, 95],
       [96, 61, 50, 76, 72],
       [90, 85, 64, 73, 93],
       [67, 67, 56, 65, 62],
       [72, 73, 91, 55, 77],
       [69, 86, 64, 70, 60],
       [78, 97, 99, 89, 99],
       [62, 72, 98, 85, 58],
       [61, 81, 61, 88, 63],
       [77, 75, 65, 79, 56],
       [94, 84, 68, 81, 61],
       [89, 77, 78, 64, 65],
       [99, 91, 62, 78, 93],
       [97, 76, 70, 56, 63],
       [99, 78, 69, 97, 88],
       [94, 64, 94, 79, 90],
       [61, 69, 93, 75, 92],
       [79, 82, 55, 82, 88],
       [81, 86, 68, 99, 59],
       [78, 60, 78, 93, 76],
       [84, 78, 62, 61, 86],
       [82, 67, 75, 96, 61],
       [78, 51, 50, 76, 65],
       [56, 94, 66, 56, 55],
       [95, 88, 59, 77, 97],
       [68, 63, 89, 78, 88],
       [53, 58, 60, 79, 62],
       [65, 76

In [11]:
scores[0:3]

array([[78, 82, 93, 94, 73],
       [51, 76, 70, 78, 58],
       [93, 55, 54, 81, 64]])

In [12]:
scores[0:3,0]

array([78, 51, 93])

In [13]:
scores[0:3,1]

array([82, 76, 55])

In [14]:
scores[0:6]

array([[78, 82, 93, 94, 73],
       [51, 76, 70, 78, 58],
       [93, 55, 54, 81, 64],
       [54, 52, 88, 51, 65],
       [79, 99, 91, 72, 65],
       [96, 77, 84, 54, 60]])

In [15]:
scores[0:4,2]

array([93, 70, 54, 88])